### ISSUE TITLE
Test mailers

### ISSUE THREAD

**Issue by drewmoore** [drewmoore/partybassics#3]
Check with mailgun, too.

**Comment by drewmoore** [comment]
```
2016-06-05T00:13:05.334293+00:00 app[web.1]: Started POST "/emails/create" for 104.186.57.0 at 2016-06-05 00:13:05 +0000
2016-06-05T00:13:05.344581+00:00 app[web.1]: Processing by EmailsController#create as HTML
2016-06-05T00:13:05.344619+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"######", "subject"=>"PB Test", "text"=>"Hey does pb work?", "commit"=>"Send It!"}
2016-06-05T00:13:05.368892+00:00 app[web.1]: Completed 500 Internal Server Error in 24ms
2016-06-05T00:13:05.374808+00:00 app[web.1]: 
2016-06-05T00:13:05.374818+00:00 app[web.1]: NoMethodError (undefined method `text' for nil:NilClass):
2016-06-05T00:13:05.374819+00:00 app[web.1]:   app/mailers/custom_mailer.rb:17:in `mass_email'
2016-06-05T00:13:05.374820+00:00 app[web.1]:   app/controllers/emails_controller.rb:12:in `block in create'
2016-06-05T00:13:05.374820+00:00 app[web.1]:   app/controllers/emails_controller.rb:11:in `create'
2016-06-05T00:13:05.374821+00:00 app[web.1]: 
2016-06-05T00:13:05.374822+00:00 app[web.1]: 
```

**Comment by drewmoore** [comment]
Emails being sent but look bad.

**Comment by drewmoore** [comment]
Emails looking fine, but found out assets are being deleted. Not surprise. Must set up assets bucket to avoid this.

**Comment by drewmoore** [comment]
Also, when domain is back on, mailgun needs the data to plug in.

**Comment by drewmoore** [comment]
Awaiting domain renewal and mail records filled out.

**Comment by drewmoore** [comment]
Event mailer still having problems because of needing to be on s3 and needing imageMagick

**Comment by drewmoore** [comment]
Below works fine with local files. S3 buckets, something else needed, not sure:

```
    def is_landscape? picture
      image = MiniMagick::Image.open(picture.path)
      image[:width] > image[:height]
    end
```

`MiniMagick::Image.open(picture.path)` is the culprit

See: https://github.com/carrierwaveuploader/carrierwave/issues/859

**Comment by drewmoore** [comment]
On image upload, try using the local tmp file for the picture.path.

**Comment by drewmoore** [comment]
Current email on dev:

![image](https://cloud.githubusercontent.com/assets/6342149/16625169/1106d060-4369-11e6-8eb5-2198bd97b1c0.png)

**Comment by drewmoore** [comment]
Still being clipped in my email client.

**Comment by drewmoore** [comment]
Most recent with a minimum height set (no text for event, just empty and flyer):

![image](https://cloud.githubusercontent.com/assets/6342149/16657790/5bb9ef64-4429-11e6-887a-cbd8a1398eef.png)

**Comment by drewmoore** [comment]
Depends on #10 from hereon, because this feature isn't much use without FB.

**Comment by drewmoore** [comment]
Tested with real event from FB. Satisfactory until further notice.
